// Generated by CoffeeScript 1.6.3
module.exports = {
  createServer: function(opts) {
    var app, connect, server;
    connect = require('connect');
    app = connect();
    app.use(connect.logger('dev'));
    app.use(require('./middleware')({
      patch: true
    }));
    if (opts.user && opts.pass) {
      app.use(connect.basicAuth(opts.user, opts.pass));
    }
    app.use(connect["static"](process.cwd()));
    app.use(connect.directory(process.cwd(), {
      hidden: true
    }));
    server = require('http').createServer(app);
    server.run = function() {
      return server.listen(3000, '0.0.0.0', function() {
        return console.log('bebop listening on 0.0.0.0:3000');
      });
    };
    return server;
  }
};

/*
//@ sourceMappingURL=server.map
*/
