// Generated by CoffeeScript 1.6.3
module.exports = {
  createServer: function() {
    var BasicStrategy, app, connect, passport, server;
    connect = require("connect");
    passport = require("passport");
    BasicStrategy = require("passport-http").BasicStrategy;
    passport.use(new BasicStrategy({}, function(username, password, done) {
      if (password !== "beepboop") {
        return done(null, false);
      } else {
        return done(null, {});
      }
    }));
    app = connect();
    app.use(connect.logger("dev"));
    app.use(passport.initialize());
    app.use(passport.authenticate("basic", {
      session: false
    }));
    app.use(connect["static"](process.cwd()));
    app.use(connect.directory(process.cwd(), {
      hidden: true
    }));
    server = require("http").createServer(app);
    server.run = function() {
      return server.listen(3000, "0.0.0.0", function() {
        return console.log("bebop listening on 0.0.0.0:3000");
      });
    };
    return server;
  }
};

/*
//@ sourceMappingURL=server.map
*/
