// Generated by CoffeeScript 1.6.3
var directoryFilter, fileFilter, fs, walk, watch, watchFile, watching;

walk = function(dir, callback) {
  var stream;
  stream = require("readdirp")({
    root: dir,
    directoryFilter: directoryFilter,
    fileFilter: fileFilter
  });
  return stream.on("data", function(file) {
    return callback(file.fullPath);
  });
};

watchFile = function(filename, callback) {
  if (watching[filename]) {
    watching[filename].close();
  }
  return watching[filename] = fs.watch(filename, function() {
    callback(filename);
    return watchFile(filename, callback);
  });
};

watch = function(dir, callback) {
  return walk(dir, function(filename) {
    return watchFile(filename, callback);
  });
};

fs = require("fs");

directoryFilter = ["!node_modules", "!.git"];

fileFilter = ["!package.json", "!.*", "!npm-debug.log", "!Cakefile", "!README.md"];

watching = {};

watch.watchFile = watchFile;

watch.walk = walk;

module.exports = watch;

/*
//@ sourceMappingURL=watch.map
*/
