# Generated by CoffeeScript 1.6.3
path = require("path")
vm = require("vm")
module.exports = (callback) ->
  hooks = undefined
  idx = undefined
  method = undefined
  methods = undefined
  updateHooks = undefined
  _results = undefined
  hooks = {}
  updateHooks = ->
    ext = undefined
    handler = undefined
    _ref = undefined
    _results = undefined
    _ref = require.extensions
    _results = []
    for ext of _ref
      handler = _ref[ext]
      _results.push ((ext, handler) ->
        if hooks[ext] isnt require.extensions[ext]
          hooks[ext] = require.extensions[ext] = (module, filename) ->
            unless module.loaded
              callback module.filename
              handler module, filename
              updateHooks()
      )(ext, handler)
    _results

  updateHooks()
  methods =
    createScript: 1
    runInThisContext: 1
    runInNewContext: 2
    runInContext: 2

  _results = []
  for method of methods
    idx = methods[method]
    _results.push ((method, idx) ->
      original = undefined
      original = vm[method]
      vm[method] = ->
        filename = undefined
        callback filename  if filename = arguments_[idx]
        original.apply vm, arguments_
    )(method, idx)
  _results

#
#//@ sourceMappingURL=watch.map
#
